# Generated by Django 3.1.6 on 2021-02-08 17:11

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', main_app.models.NameField(max_length=100)),
                ('nickname', models.CharField(default=main_app.models.NameField(max_length=100), max_length=100)),
                ('pokedex_no', models.IntegerField(blank=True)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=250)),
            ],
        ),
    ]
