# Generated by Django 3.1.6 on 2021-02-08 17:25

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='nickname',
            field=models.CharField(blank=True, default=main_app.models.NameField(max_length=100), max_length=100),
        ),
    ]
