# Generated by Django 3.1.6 on 2021-02-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210208_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='nickname',
        ),
    ]
