# Generated by Django 3.1.6 on 2021-02-08 19:02

from django.db import migrations
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210208_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=main_app.models.NameField(max_length=100),
        ),
    ]
