# Generated by Django 3.1.6 on 2021-02-09 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_battles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Battles',
            new_name='Battle',
        ),
    ]
