# Generated by Django 3.1.6 on 2021-02-09 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210209_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Battle',
            new_name='Battles',
        ),
    ]
