# Generated by Django 3.1.6 on 2021-02-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210209_0214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Battles',
            new_name='Battle',
        ),
    ]
