# Generated by Django 3.1.6 on 2021-02-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_battle_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='date',
            field=models.DateField(verbose_name='battle date'),
        ),
    ]
